"""add Role

Revision ID: 11744c6ae88e
Revises: f801c046f82d
Create Date: 2021-06-25 15:20:01.236698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11744c6ae88e'
down_revision = 'f801c046f82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.String(length=64), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
