"""add email verify.

Revision ID: 5a3717faba5b
Revises: 85fda37ac7cc
Create Date: 2021-06-24 16:16:11.546235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3717faba5b'
down_revision = '85fda37ac7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmd', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmd')
    # ### end Alembic commands ###
